coverage:
  range: 85..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 85
        threshold: 5
        base: auto
    patch:
      default:
        target: 50
        threshold: 5
        base: auto
