name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: yarn build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Build
        run: yarn docs
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Test
        run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, build-docs, lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
